//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Learn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikel()
        {
            this.Bestelldetails = new HashSet<Bestelldetails>();
        }
    
        public int Artikel_Nr { get; set; }
        public string Artikelname { get; set; }
        public Nullable<int> Lieferanten_Nr { get; set; }
        public Nullable<int> Kategorie_Nr { get; set; }
        public string Liefereinheit { get; set; }
        public Nullable<decimal> Einzelpreis { get; set; }
        public Nullable<short> Lagerbestand { get; set; }
        public Nullable<short> BestellteEinheiten { get; set; }
        public Nullable<short> Mindestbestand { get; set; }
        public bool Auslaufartikel { get; set; }
    
        public virtual Kategorien Kategorien { get; set; }
        public virtual Lieferanten Lieferanten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelldetails> Bestelldetails { get; set; }
    }
}
