//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Learn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelldetails
    {
        public int Bestell_Nr { get; set; }
        public int Artikel_Nr { get; set; }
        public decimal Einzelpreis { get; set; }
        public short Anzahl { get; set; }
        public float Rabatt { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Bestellungen Bestellungen { get; set; }
    }
}
