//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Learn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellungen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bestellungen()
        {
            this.Bestelldetails = new HashSet<Bestelldetails>();
        }
    
        public int Bestell_Nr { get; set; }
        public string Kunden_Code { get; set; }
        public Nullable<int> Personal_Nr { get; set; }
        public Nullable<System.DateTime> Bestelldatum { get; set; }
        public Nullable<System.DateTime> Lieferdatum { get; set; }
        public Nullable<System.DateTime> Versanddatum { get; set; }
        public Nullable<int> VersandUeber { get; set; }
        public Nullable<decimal> Frachtkosten { get; set; }
        public string Empfaenger { get; set; }
        public string Straße { get; set; }
        public string Ort { get; set; }
        public string Region { get; set; }
        public string PLZ { get; set; }
        public string Bestimmungsland { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelldetails> Bestelldetails { get; set; }
        public virtual Kunden Kunden { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Versandfirmen Versandfirmen { get; set; }
    }
}
