//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Learn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nordwind2021Entities : DbContext
    {
        public nordwind2021Entities()
            : base("name=nordwind2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikel> Artikel { get; set; }
        public virtual DbSet<Bestelldetails> Bestelldetails { get; set; }
        public virtual DbSet<Bestellungen> Bestellungen { get; set; }
        public virtual DbSet<Kategorien> Kategorien { get; set; }
        public virtual DbSet<Kunden> Kunden { get; set; }
        public virtual DbSet<Lieferanten> Lieferanten { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Versandfirmen> Versandfirmen { get; set; }
    }
}
