//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Learn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Bestellungen = new HashSet<Bestellungen>();
            this.Personal1 = new HashSet<Personal>();
        }
    
        public int Personal_Nr { get; set; }
        public string Nachname { get; set; }
        public string Vorname { get; set; }
        public string Position { get; set; }
        public string Anrede { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public Nullable<System.DateTime> Einstellung { get; set; }
        public string Straße { get; set; }
        public string Ort { get; set; }
        public string Region { get; set; }
        public string PLZ { get; set; }
        public string Land { get; set; }
        public string TelefonPrivat { get; set; }
        public string DurchwahlBuero { get; set; }
        public byte[] Foto { get; set; }
        public string Bemerkungen { get; set; }
        public Nullable<int> Vorgesetzter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellungen> Bestellungen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal1 { get; set; }
        public virtual Personal Personal2 { get; set; }
    }
}
